services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DATABASE:-booking_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2
    container_name: redis-booking
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper-booking
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000

  kafka-broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker-booking
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  keycloak-db:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8091:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-db
# http://localhost:8091/admin/master/console/

  # api-gateway:
  #   build:
  #     context: ./apigateway
  #     dockerfile: Dockerfile
  #   container_name: api-gateway
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     INVENTORY_SERVICE_URL: http://inventory-service:8080
  #     BOOKING_SERVICE_URL: http://booking-service:8081
  #     PAYMENT_SERVICE_URL: http://payment-service:8085
  #     TRIP_SERVICE_URL: http://trip-service:8086
  #     KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/ticketing-security-realm/protocol/openid-connect/certs
  #     KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/ticketing-security-realm
  #   depends_on:
  #     - postgres

  # inventory-service:
  #   build:
  #     context: ./inventory-service
  #     dockerfile: Dockerfile
  #   container_name: inventory-service
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #   depends_on:
  #     - postgres

  # user-service:
  #   build:
  #     context: ./user-service
  #     dockerfile: Dockerfile
  #   container_name: user-service
  #   ports:
  #     - "8083:8082"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
  #     KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/ticketing-security-realm
  #     KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/ticketing-security-realm/protocol/openid-connect/certs
  #   depends_on:
  #     - postgres
  #     - kafka-broker

  # booking-service:
  #   build:
  #     context: ./booking-service
  #     dockerfile: Dockerfile
  #   container_name: booking-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
  #     INVENTORY_SERVICE_URL: http://inventory-service:8080
  #   depends_on:
  #     - postgres
  #     - kafka-broker

  # order-service:
  #   build:
  #     context: ./order-service
  #     dockerfile: Dockerfile
  #   container_name: order-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
  #     INVENTORY_SERVICE_URL: http://inventory-service:8080
  #   depends_on:
  #     - postgres
  #     - kafka-broker

  # payment-service:
  #   build:
  #     context: ./payment-service
  #     dockerfile: Dockerfile
  #   container_name: payment-service
  #   ports:
  #     - "8085:8085"
  #   env_file:
  #     - .env
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #     ORDER_SERVICE_URL: http://order-service:8082
  #     STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  #     STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  #   depends_on:
  #     - postgres
  #     - kafka-broker

  # trip-service:
  #   build:
  #     context: ./trip-service
  #     dockerfile: Dockerfile
  #   container_name: trip-service
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trip_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  redis_data:
