spring:
  application:
    name: booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8091/realms/ticketing-security-realm/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8091/realms/ticketing-security-realm}
server:
  port: 8081

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8080}
  grpc:
    host: ${INVENTORY_SERVICE_HOST:localhost}
    port: ${INVENTORY_SERVICE_PORT:9090}

app:
  kafka:
    booking-topic: booking

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs  

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8084}

trip:
  service:
    url: ${TRIP_SERVICE_URL:http://localhost:8085}



